services:
  frontend:
      container_name: frontend
      restart: on-failure
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - "5173:5173"
        - 3000:3000
        - 24678:24678
      volumes:
        - ./frontend:/usr/src/app
        - /usr/src/app/node_modules
      networks:
        - futureu-system
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - futureu-system
    ports:
      - "5000:5000"
networks:
  futureu-system:
    driver: bridge