services:
  frontend:
      container_name: frontend
      restart: on-failure
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - "5173:5173"
        - 3000:3000
        - 24678:24678
      volumes:
        - ./frontend:/usr/src/app
      networks:
        - futureu-system
networks:
  futureu-system:
    driver: bridge