services:
  frontend:
      container_name: frontend
      restart: on-failure
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - "5173:5173"
        - 3000:3000
        - 24678:24678
      volumes:
        - ./frontend:/usr/src/app
        - /usr/src/app/node_modules
      networks:
        - futureu-system
  api:
    container_name: api
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    volumes:
      - ./backend/api:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - futureu-system
    ports:
      - "3012:3012"
  gateway:
    container_name: gateway
    build:
      context: ./backend/gateway
      dockerfile: Dockerfile
    volumes:
      - ./backend/gateway:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - futureu-system
    ports:
      - "3011:3011"
networks:
  futureu-system:
    driver: bridge